<div class="container">
	<?php
		$this->title = "Editar";
		$this->headTitle($this->name);
		echo $this->form;
	?>

	<table class="table table-condensed table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Ação</th>
				<th>Data</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->history as $log) : ?>
				<tr>
					<td><?=$log->id?></td>
					<td><?=$log->action?></td>
					<td><?=date('d/m/Y H:m:s', strtotime($log->date_action))?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

</div>